// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AppPointServiceClient is the client API for AppPointService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppPointServiceClient interface {
	// Sends a greeting
	Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type appPointServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppPointServiceClient(cc grpc.ClientConnInterface) AppPointServiceClient {
	return &appPointServiceClient{cc}
}

func (c *appPointServiceClient) Send(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/app.point.AppPointService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppPointServiceServer is the server API for AppPointService service.
// All implementations must embed UnimplementedAppPointServiceServer
// for forward compatibility
type AppPointServiceServer interface {
	// Sends a greeting
	Send(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAppPointServiceServer()
}

// UnimplementedAppPointServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAppPointServiceServer struct {
}

func (UnimplementedAppPointServiceServer) Send(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedAppPointServiceServer) mustEmbedUnimplementedAppPointServiceServer() {}

// UnsafeAppPointServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppPointServiceServer will
// result in compilation errors.
type UnsafeAppPointServiceServer interface {
	mustEmbedUnimplementedAppPointServiceServer()
}

func RegisterAppPointServiceServer(s grpc.ServiceRegistrar, srv AppPointServiceServer) {
	s.RegisterService(&AppPointService_ServiceDesc, srv)
}

func _AppPointService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppPointServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.point.AppPointService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppPointServiceServer).Send(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// AppPointService_ServiceDesc is the grpc.ServiceDesc for AppPointService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppPointService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "app.point.AppPointService",
	HandlerType: (*AppPointServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _AppPointService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/point.proto",
}
